parameters:
#    shopping_list.example.class: Astina\ShoppingListBundle\Example

services:
#    shopping_list.example:
#        class: %shopping_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
